// eslint-disable-next-line import/prefer-default-export
export const commonConstants = {
  DOWNLOAD_FILE_START: 'DOWNLOAD_FILE_START',
  DOWNLOAD_FILE_SUCCESS: 'DOWNLOAD_FILE_SUCCESS',
  DOWNLOAD_FILE_FAIL: 'DOWNLOAD_FILE_FAIL',

  FETCH_DOWNLOAD_FILE_URL_START: 'FETCH_DOWNLOAD_FILE_URL_START',
  FETCH_DOWNLOAD_FILE_URL_SUCCESS: 'FETCH_DOWNLOAD_FILE_URL_SUCCESS',
  FETCH_DOWNLOAD_FILE_URL_FAIL: 'FETCH_DOWNLOAD_FILE_URL_FAIL',

  SEARCH_START: 'SEARCH_START',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAIL: 'SEARCH_FAIL',
};
