// eslint-disable-next-line import/prefer-default-export
export const commonConstants = {

  FETCH_ACCOUNT_START: 'FETCH_ACCOUNT_START',
  FETCH_ACCOUNT_SUCCESS: 'FETCH_ACCOUNT_SUCCESS',
  FETCH_ACCOUNT_FAIL: 'FETCH_ACCOUNT_FAIL',

  DOWNLOAD_FILE_START: 'DOWNLOAD_FILE_START',
  DOWNLOAD_FILE_SUCCESS: 'DOWNLOAD_FILE_SUCCESS',
  DOWNLOAD_FILE_FAIL: 'DOWNLOAD_FILE_FAIL',

  FETCH_DOWNLOAD_FILE_URL_START: 'FETCH_DOWNLOAD_FILE_URL_START',
  FETCH_DOWNLOAD_FILE_URL_SUCCESS: 'FETCH_DOWNLOAD_FILE_URL_SUCCESS',
  FETCH_DOWNLOAD_FILE_URL_FAIL: 'FETCH_DOWNLOAD_FILE_URL_FAIL',

  GET_ACCOUNT_BATCH_START: 'GET_ACCOUNT_BATCH_START',
  GET_ACCOUNT_BATCH_SUCCESS: 'GET_ACCOUNT_BATCH_SUCCESS',
  GET_ACCOUNT_BATCH_FAIL: 'GET_ACCOUNT_BATCH_FAIL',
};
