// eslint-disable-next-line import/prefer-default-export
export const commonConstants = {
  DOWNLOAD_FILE_START: 'DOWNLOAD_FILE_START',
  DOWNLOAD_FILE_SUCCESS: 'DOWNLOAD_FILE_SUCCESS',
  DOWNLOAD_FILE_FAIL: 'DOWNLOAD_FILE_FAIL',

  FETCH_DOWNLOAD_FILE_URL_START: 'FETCH_DOWNLOAD_FILE_URL_START',
  FETCH_DOWNLOAD_FILE_URL_SUCCESS: 'FETCH_DOWNLOAD_FILE_URL_SUCCESS',
  FETCH_DOWNLOAD_FILE_URL_FAIL: 'FETCH_DOWNLOAD_FILE_URL_FAIL',

  SEARCH_PEOPLE_START: 'SEARCH_PEOPLE_START',
  SEARCH_PEOPLE_SUCCESS: 'SEARCH_PEOPLE_SUCCESS',
  SEARCH_PEOPLE_FAIL: 'SEARCH_PEOPLE_FAIL',

  SEARCH_TAGS_START: 'SEARCH_TAGS_START',
  SEARCH_TAGS_SUCCESS: 'SEARCH_TAGS_SUCCESS',
  SEARCH_TAGS_FAIL: 'SEARCH_TAGS_FAIL',

  SEARCH_SCHOOLS_START: 'SEARCH_SCHOOLS_START',
  SEARCH_SCHOOLS_SUCCESS: 'SEARCH_SCHOOLS_SUCCESS',
  SEARCH_SCHOOLS_FAIL: 'SEARCH_SCHOOLS_FAIL',

  SEARCH_COURSES_START: 'SEARCH_COURSES_START',
  SEARCH_COURSES_SUCCESS: 'SEARCH_COURSES_SUCCESS',
  SEARCH_COURSES_FAIL: 'SEARCH_COURSES_FAIL',

  SEARCH_NOTES_START: 'SEARCH_NOTES_START',
  SEARCH_NOTES_SUCCESS: 'SEARCH_NOTES_SUCCESS',
  SEARCH_NOTES_FAIL: 'SEARCH_NOTES_FAIL',

  SEARCH_TEMPLATES_START: 'SEARCH_TEMPLATES_START',
  SEARCH_TEMPLATES_SUCCESS: 'SEARCH_TEMPLATES_SUCCESS',
  SEARCH_TEMPLATES_FAIL: 'SEARCH_TEMPLATES_FAIL',
};
