// eslint-disable-next-line import/prefer-default-export
export const courseConstants = {
  GET_SCHOOL_COURSE_START: 'GET_SCHOOL_COURSE_START',
  GET_SCHOOL_COURSE_SUCCESS: 'GET_SCHOOL_COURSE_SUCCESS',
  GET_SCHOOL_COURSE_FAIL: 'GET_SCHOOL_COURSE_FAIL',

  GET_COURSE_START: 'GET_COURSE_START',
  GET_COURSE_SUCCESS: 'GET_COURSE_SUCCESS',
  GET_COURSE_FAIL: 'GET_COURSE_FAIL',
};
