export const authConstants = {
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',

  AUTH_LOGIN_FAIL: 'AUTH_LOGIN_FAIL',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',

  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
};

export const userConstants = {
  READ_SELF_ACCOUNT_START: 'READ_SELF_ACCOUNT_START',
  READ_SELF_ACCOUNT_SUCCESS: 'READ_SELF_ACCOUNT_SUCCESS',
  READ_SELF_ACCOUNT_FAIL: 'READ_SELF_ACCOUNT_FAIL',

  READ_OTHERS_ACCOUNT_START: 'READ_OTHERS_ACCOUNT_START',
  READ_OTHERS_ACCOUNT_SUCCESS: 'READ_OTHERS_ACCOUNT_SUCCESS',
  READ_OTHERS_ACCOUNT_FAIL: 'READ_OTHERS_ACCOUNT_FAIL',

  EDIT_SELF_PASSWORD_START: 'EDIT_SELF_PASSWORD_START',
  EDIT_SELF_PASSWORD_SUCCESS: 'EDIT_SELF_PASSWORD_SUCCESS',
  EDIT_SELF_PASSWORD_FAIL: 'EDIT_SELF_PASSWORD_FAIL',

  EDIT_SELF_ACCOUNT_START: 'EDIT_SELF_ACCOUNT_START',
  EDIT_SELF_ACCOUNT_SUCCESS: 'EDIT_SELF_ACCOUNT_SUCCESS',
  EDIT_SELF_ACCOUNT_FAIL: 'EDIT_SELF_ACCOUNT_FAIL',

  FETCH_ACCOUNT_FOLLOWERS_START: 'FETCH_ACCOUNT_FOLLOWERS_START',
  FETCH_ACCOUNT_FOLLOWERS_SUCCESS: 'FETCH_ACCOUNT_FOLLOWERS_SUCCESS',
  FETCH_ACCOUNT_FOLLOWERS_FAIL: 'FETCH_ACCOUNT_FOLLOWERS_FAIL',

  FETCH_ACCOUNT_FOLLOWINGS_START: 'FETCH_ACCOUNT_FOLLOWINGS_START',
  FETCH_ACCOUNT_FOLLOWINGS_SUCCESS: 'FETCH_ACCOUNT_FOLLOWINGS_SUCCESS',
  FETCH_ACCOUNT_FOLLOWINGS_FAIL: 'FETCH_ACCOUNT_FOLLOWINGS_FAIL',

  CHECK_ACCOUNT_FOLLOWING_START: 'CHECK_ACCOUNT_FOLLOWING_START',
  CHECK_ACCOUNT_FOLLOWING_SUCCESS: 'CHECK_ACCOUNT_FOLLOWING_SUCCESS',
  CHECK_ACCOUNT_FOLLOWING_FAIL: 'CHECK_ACCOUNT_FOLLOWING_FAIL',

  ADD_ACCOUNT_FOLLOWING_START: 'ADD_ACCOUNT_FOLLOWING_START',
  ADD_ACCOUNT_FOLLOWING_SUCCESS: 'ADD_ACCOUNT_FOLLOWING_SUCCESS',
  ADD_ACCOUNT_FOLLOWING_FAIL: 'ADD_ACCOUNT_FOLLOWING_FAIL',

  DELETE_ACCOUNT_FOLLOWING_START: 'DELETE_ACCOUNT_FOLLOWING_START',
  DELETE_ACCOUNT_FOLLOWING_SUCCESS: 'DELETE_ACCOUNT_FOLLOWING_SUCCESS',
  DELETE_ACCOUNT_FOLLOWING_FAIL: 'DELETE_ACCOUNT_FOLLOWING_FAIL',
};
