export const authConstants = {
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',

  AUTH_LOGIN_FAIL: 'AUTH_LOGIN_FAIL',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',

  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
};

export const userConstants = {
  EDIT_SELF_PASSWORD_START: 'EDIT_SELF_PASSWORD_START',
  EDIT_SELF_PASSWORD_SUCCESS: 'EDIT_SELF_PASSWORD_SUCCESS',
  EDIT_SELF_PASSWORD_FAIL: 'EDIT_SELF_PASSWORD_FAIL',

  EDIT_SELF_ACCOUNT_START: 'EDIT_SELF_ACCOUNT_START',
  EDIT_SELF_ACCOUNT_SUCCESS: 'EDIT_SELF_ACCOUNT_SUCCESS',
  EDIT_SELF_ACCOUNT_FAIL: 'EDIT_SELF_ACCOUNT_FAIL',

  USER_BROWSE_ANNOUNCEMENT_SUCCESS: 'USER_BROWSE_ANNOUNCEMENT_SUCCESS',
  USER_BROWSE_ANNOUNCEMENT_FAIL: 'USER_BROWSE_ANNOUNCEMENT_FAIL',
  USER_READ_NOTIFY: 'USER_READ_NOTIFY',
  USER_READ_NOTIFY_FAIL: 'USER_READ_NOTIFY_FAIL',

  READ_OTHERS_ACCOUNT_START: 'READ_OTHERS_ACCOUNT_START',
  READ_OTHERS_ACCOUNT_SUCCESS: 'READ_OTHERS_ACCOUNT_SUCCESS',
  READ_OTHERS_ACCOUNT_FAIL: 'READ_OTHERS_ACCOUNT_FAIL',
};
