// eslint-disable-next-line import/prefer-default-export
export const noteConstants = {
  ADD_NOTE_START: 'ADD_NOTE_START',
  ADD_NOTE_SUCCESS: 'ADD_NOTE_SUCCESS',
  ADD_NOTE_FAIL: 'ADD_NOTE_FAIL',

  SEARCH_NOTE_START: 'SEARCH_NOTE_START',
  SEARCH_NOTE_SUCCESS: 'SEARCH_NOTE_SUCCESS',
  SEARCH_NOTE_FAIL: 'SEARCH_NOTE_FAIL',

  BROWSE_NOTE_BY_TAG_START: 'BROWSE_NOTE_BY_TAG_START',
  BROWSE_NOTE_BY_TAG_SUCCESS: 'BROWSE_NOTE_BY_TAG_SUCCESS',
  BROWSE_NOTE_BY_TAG_FAIL: 'BROWSE_NOTE_BY_TAG_FAIL',

  BROWSE_NOTE_BY_COURSE_START: 'BROWSE_NOTE_BY_COURSE_START',
  BROWSE_NOTE_BY_COURSE_SUCCESS: 'BROWSE_NOTE_BY_COURSE_SUCCESS',
  BROWSE_NOTE_BY_COURSE_FAIL: 'BROWSE_NOTE_BY_COURSE_FAIL',

  BROWSE_NOTE_HOT_START: 'BROWSE_NOTE_HOT_START',
  BROWSE_NOTE_HOT_SUCCESS: 'BROWSE_NOTE_HOT_SUCCESS',
  BROWSE_NOTE_HOT_FAIL: 'BROWSE_NOTE_HOT_FAIL',

  READ_NOTE_START: 'READ_NOTE_START',
  READ_NOTE_SUCCESS: 'READ_NOTE_SUCCESS',
  READ_NOTE_FAIL: 'READ_NOTE_FAIL',

  CHECK_NOTE_SAVED_OR_NOT_START: 'CHECK_NOTE_SAVED_OR_NOT_START',
  CHECK_NOTE_SAVED_OR_NOT_SUCCESS: 'CHECK_NOTE_SAVED_OR_NOT_SUCCESS',
  CHECK_NOTE_SAVED_OR_NOT_FAIL: 'CHECK_NOTE_SAVED_OR_NOT_FAIL',

  ADD_NOTE_SAVED_START: 'ADD_NOTE_SAVED_START',
  ADD_NOTE_SAVED_SUCCESS: 'ADD_NOTE_SAVED_SUCCESS',
  ADD_NOTE_SAVED_FAIL: 'ADD_NOTE_SAVED_FAIL',

  REMOVE_NOTE_SAVED_START: 'REMOVE_NOTE_SAVED_START',
  REMOVE_NOTE_SAVED_SUCCESS: 'REMOVE_NOTE_SAVED_SUCCESS',
  REMOVE_NOTE_SAVED_FAIL: 'REMOVE_NOTE_SAVED_FAIL',

  EDIT_NOTE_START: 'EDIT_NOTE_START',
  EDIT_NOTE_SUCCESS: 'EDIT_NOTE_SUCCESS',
  EDIT_NOTE_FAIL: 'EDIT_NOTE_FAIL',
};
