// eslint-disable-next-line import/prefer-default-export
export const tagConstants = {
  BROWSE_TAG_START: 'BROWSE_TAG_START',
  BROWSE_TAG_SUCCESS: 'BROWSE_TAG_SUCCESS',
  BROWSE_TAG_FAIL: 'BROWSE_TAG_FAIL',

  GET_TAG_START: 'GET_TAG_START',
  GET_TAG_SUCCESS: 'GET_TAG_SUCCESS',
  GET_TAG_FAIL: 'GET_TAG_FAIL',

  ADD_TAG_START: 'GET_TAG_START',
  ADD_TAG_SUCCESS: 'GET_TAG_SUCCESS',
  ADD_TAG_FAIL: 'GET_TAG_FAIL',
};
